/**
 * This Record is used to store all the file endings of possible analysis files.
 */
export const languages: Record<string, string> = {
    "ABAP": ", **.abap",
    "Assembly": ", **.asm",
    "Ballerina": ", **.bal",
    "C": ", **.c",
    "C#": ", **.cs",
    "C++": ", **.cpp",
    "CMake": ", CMakeLists.txt",
    "Cairo": ", **.cairo",
    "Clojure": ", **.clj",
    "CoffeeScript": ", **.coffee",
    "Coq": ", **.v",
    "Crystal": ", **.cr",
    "CSS": ", **.css",
    "Cython": ", **.pyx",
    "Dart": ", **.dart",
    "Dhall": ", **.dhall",
    "Elixir": ", **.ex",
    "Elm": ", **.elm",
    "Emacs Lisp": ", **.el",
    "Erlang": ", **.erl",
    "F*": ", **.fst",
    "Fortran": ", **.f90",
    "GAP": ", **.g",
    "Game Maker Language": ", **.gml",
    "GLSL": ", **.glsl",
    "Go": ", **.go",
    "Groovy": ", **.groovy",
    "Haskell": ", **.hs",
    "Haxe": ", **.hx",
    "HCL": ", **.hcl",
    "HTML": ", **.html",
    "Jinja": ", **.jinja",
    "Java": ", **.java",
    "JavaScript": ", **.js",
    "Jupyter Notebook": ", **.ipynb",
    "Julia": ", **.jl",
    "Kotlin": ", **.kt",
    "Lua": ", **.lua",
    "M": ", **.m",
    "MATLAB": ", **.m",
    "mdsvex": ", **.svx",
    "Nasal": ", **.nas",
    "Nextflow": ", **.nf",
    "Nix": ", **.nix",
    "Objective-C": ", **.m",
    "Objective-C++": ", **.mm",
    "OCaml": ", **.ml",
    "Open Policy Agent": ", **.rego",
    "Perl": ", **.pl",
    "PHP": ", **.php",
    "PLpgSQL": ", **.sql",
    "Pony": ", **.pony",
    "Prolog": ", **.pl",
    "Pug": ", **.pug",
    "Puppet": ", **.pp",
    "Python": ", **.py",
    "R": ", **.r",
    "Reason": ", **.re",
    "Rich Text Format": ", **.rtf",
    "Roff": ", **.roff",
    "Ruby": ", **.rb",
    "Rust": ", **.rs",
    "Scala": ", **.scala",
    "SCSS": ", **.scss",
    "Scheme": ", **.scm",
    "ShaderLab": ", **.shader",
    "Shell": ", **.sh",
    "Smalltalk": ", **.st",
    "Smarty": ", **.tpl",
    "Solidity": ", **.sol",
    "Sql": ", **.sql",
    "Stata": ", **.do",
    "Svelte": ", **.svelte",
    "Swift": ", **.swift",
    "TeX": ", **.tex",
    "TSQL": ", **.sql",
    "TypeScript": ", **.ts",
    "Vim Script": ", **.vim",
    "Verilog": ", **.v",
    "Vue": ", **.vue",
    "XProc": ", **.xpl",
    "Xtend": ", **.xtend",
    "YAML": ", **.yaml"
};


export class DataHelper{
    private static data_points: Record<string, DataPoint> = require("../../../src/data/data.json");

    static get getData(): Record<string, DataPoint>  {
        return this.data_points;
    }
}